O4P/O4P/urls.py
from django.contrib import admin
from adminplus.sites import AdminSitePlus
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static
from accounts.admin import custom_admin_site

urlpatterns = [
    path('admin/', custom_admin_site.urls),
    #path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('', include('patients.urls')),
    path('', include('home.urls')),
    path('games/', include('games.urls')),
    path('auth/', include('allauth.urls')),
    path('', include('appointments.urls')),
    path('', include('therapists.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

O4P/patients/urls.py
from django.urls import path, include
from . import views
from patients.views import AssignGameView, RemoveAssignedGameView

urlpatterns = [
    path('patients', views.PatientsListView.as_view(), name="patients.list"),
    path('patients/create/', views.PatientInformationCreateView.as_view(), name="patients.create"),
    path('patients/<int:pk>/', views.PatientDetailView.as_view(), name="patients.details"),
    
    path('patients/<int:pk>/edit/', views.PatientsUpdateView.as_view(), name="patients.update"),
    path('patients/<int:pk>/delete/', views.PatientsDeleteView.as_view(), name="patients.delete"),

    path('patients/notes/<int:pk>/', views.NoteDetailView.as_view(), name='notes.details'),
    path('patients/notes/<int:pk>/create/', views.NoteCreateView.as_view(), name='notes.create'),
    path('patients/notes/<int:pk>/edit', views.NotesUpdateView.as_view(), name="notes.update"),
    path('patients/notes/<int:pk>/delete', views.NotesDeleteView.as_view(), name="notes.delete"), 

    path('<int:patient_id>/assign_game/', AssignGameView.as_view(), name='assign_game'),
    path('<int:patient_id>/remove_assigned_game/<int:assigned_game_id>/', RemoveAssignedGameView.as_view(), name='remove_assigned_game'),
]

O4P/accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import RegexValidator
from datetime import date
from simple_history.models import HistoricalRecords
from .nationalities import NATIONALITIES_duble_tuple_for as Nationalities

#GEOGRAPHY MODELS FOR FORMS
class Province(models.Model):
    code = models.CharField(max_length=10, unique=True)
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Municipality(models.Model):
    code = models.CharField(max_length=10, unique=True)
    name = models.CharField(max_length=100)
    province = models.ForeignKey(Province, on_delete=models.CASCADE, related_name="municipalities")

    def __str__(self):
        return self.name
    
class BaseInformation(models.Model):
    account_id = models.ForeignKey(User, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=50) 
    middle_name = models.CharField(max_length=50, blank=True, null=True) 
    last_name = models.CharField(max_length=50)  
    date_of_birth = models.DateField()  

    @property
    def age(self):
        today = date.today()
        age = today.year - self.date_of_birth.year
        if (today.month, today.day) < (self.date_of_birth.month, self.date_of_birth.day):
            age -= 1
        return age  
             
    contact_number = models.CharField(
        max_length=13,  
        validators=[
            RegexValidator(
                regex=r'^(\+63|0)9\d{9}$',  
                message="Phone number must be entered in the format: '+639123456789' or '09123456789'."
            )
        ]
    )
    
    sex_choices = (
        ('M', 'Male'),
        ('F', 'Female')
    )
    sex = models.CharField(max_length=1, choices=sex_choices, blank=True, null=True)    
    province = models.ForeignKey(Province, on_delete=models.SET_NULL, null=True, blank=True, related_name="%(class)s_residents")
    municipality = models.ForeignKey(Municipality, on_delete=models.SET_NULL, null=True, blank=True, related_name="%(class)s_residents")
    nationality = models.CharField(
        max_length=30,
        choices=Nationalities, 
        blank=True,
        null=True
    )
    history = HistoricalRecords(inherit=True)          
    
    class Meta:
        abstract = True
        verbose_name = "User Information"
        verbose_name_plural = "User Information"

        indexes = [
        models.Index(fields=['account_id']),
    ]
    
    def __str__(self):
        return f"{self.first_name} {self.middle_name} - {self.last_name} - {self.contact_number}"
    
class TherapistInformation(BaseInformation):
    specialization = models.CharField(max_length=100, blank=True, null=True)  

    class Meta:
        verbose_name = "Therapist Information"
        verbose_name_plural = "Therapist Information"

class AssistantInformation(BaseInformation):

    class Meta:
        verbose_name = "Assistant Information"
        verbose_name_plural = "Assistant Information"
        

class GuardianInformation(BaseInformation):

    class Meta:
        verbose_name = "Guardian Information"
        verbose_name_plural = "Guardian Information"

O4P/patients/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth.models import Group
from accounts.models import BaseInformation
from django.core.validators import RegexValidator
# Create your models here.

class Guardian(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username
    
class PatientInformation(BaseInformation):              
    diagnosis = models.CharField(max_length=50)    
    mother_name = models.CharField(max_length=50)
    mother_number = models.CharField(
        max_length=13,  
        validators=[
            RegexValidator(
                regex=r'^(\+63|0)9\d{9}$',  
                message="Phone number must be entered in the format: '+639123456789' or '09123456789'."
            )
        ]
    )
    father_name = models.CharField(max_length=50)
    father_number = models.CharField(
        max_length=13,  
        validators=[
            RegexValidator(
                regex=r'^(\+63|0)9\d{9}$',  
                message="Phone number must be entered in the format: '+639123456789' or '09123456789'."
            )
        ]
    )
    referring_doctor = models.CharField(max_length=50)
    school = models.CharField(max_length=50, blank=True, null=True)
    initial_evaluation = models.CharField(max_length=100)
    relationship_to_guardian = models.CharField(max_length=50)
    contact_number = None
    religion = models.CharField(max_length=50, null=True) 
    
    class Meta:
        verbose_name = "Patient Information"
        verbose_name_plural = "Patient Information"
    
    def __str__(self):
        return f"{self.first_name} {self.middle_name} - {self.last_name} - {self.contact_number}"

class PatientNotes(models.Model):
    patient = models.ForeignKey(PatientInformation, on_delete=models.CASCADE, related_name="notes")
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    title = models.CharField(max_length=100)  
    session_date = models.DateField()         
    content = models.TextField()               

    class Meta:
        verbose_name = "Patient Notes"
        verbose_name_plural = "Patient Notes"
        
    def __str__(self):
        return f"{self.title} - {self.patient.id} - {self.session_date}"
    

O4P/patients/views.py
from django.views.generic import ListView, DetailView, CreateView, UpdateView
from django.views.generic.edit import DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import PatientInformation
from .models import PatientNotes
from .forms import PatientInformationForm
from .forms import PatientNotesForm
from .models import Guardian
from core.mixins import UserRoleMixin
from core.mixins import RolePermissionRequiredMixin
from django.core.exceptions import PermissionDenied
from django.shortcuts import get_object_or_404
from django.urls import reverse
from django.shortcuts import redirect
from django.http import JsonResponse
from django.urls import reverse_lazy
from allauth.account.views import SignupView
from django.http import HttpResponseForbidden
from games.models import AssignedGame, Game
from django.views import View
from django.contrib import messages

#
# PATIENTS
#
class PatientInformationCreateView(RolePermissionRequiredMixin, CreateView):
    model = PatientInformation
    form_class = PatientInformationForm
    template_name = "patients/patients_information_form.html"
    allowed_roles = ['Guardian']
    success_url = reverse_lazy('patients.list')

    def form_valid(self, form):
        guardian = self.request.user  # The logged-in guardian
        
        # Count existing patients for this guardian
        patient_count = PatientInformation.objects.filter(account_id=guardian).count()

        if patient_count >= 10:  # Set your patient limit
            messages.error(self.request, "A guardian can have a maximum of 10 patients. Current patient count: " + str(patient_count))
            return redirect(self.request.path)  # Reload the form with an error message

        # Assign the guardian before saving
        form.instance.account_id = guardian
        return super().form_valid(form)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

    
class PatientsListView(LoginRequiredMixin, UserRoleMixin, ListView):
    model = PatientInformation
    context_object_name = "patients"
    template_name = "patients/patients_list.html"

    def get_queryset(self):
        queryset = self.get_role_based_queryset(PatientInformation)
        search_query = self.request.GET.get('q', '')

        if search_query:
            queryset = queryset.filter(
                first_name__icontains=search_query
            ) | queryset.filter(
                last_name__icontains=search_query
            ) | queryset.filter(
                diagnosis__icontains=search_query
            )
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['search_query'] = self.request.GET.get('q', '')
        return context

class PatientDetailView(LoginRequiredMixin, UserRoleMixin, DetailView,):
    model = PatientInformation
    template_name = 'patients/patients_detail.html'
    context_object_name = "patient"
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        patient = self.get_object()
        user = self.request.user

        context['patient_notes'] = PatientNotes.objects.filter(patient_id=patient)

        # Retrieve assigned games
        context['assigned_games'] = AssignedGame.objects.filter(patient=patient)
        context['available_games'] = []

        # Retrieve available games for therapists to assign
        if user.groups.filter(name='Therapist').exists():
            assigned_game_ids = AssignedGame.objects.filter(patient=patient).values_list('game_id', flat=True)
            context['available_games'] = Game.objects.exclude(id__in=assigned_game_ids)  # Exclude assigned games
        
        context['is_patient'] = user.groups.filter(name='Patient').exists()
        context['is_guardian'] = user.groups.filter(name='Guardian').exists()
        context['is_assistant'] = user.groups.filter(name='Assistant').exists()
        context['is_therapist'] = user.groups.filter(name='Therapist').exists()
        context['is_administrator'] = user.groups.filter(name='Administrator').exists()

        return context
    
    def get_queryset(self):
        return self.get_role_based_queryset(PatientInformation)
    
class PatientsUpdateView(LoginRequiredMixin, UserRoleMixin, UpdateView):
    model = PatientInformation
    form_class = PatientInformationForm
    template_name = "patients/patients_form.html"
   
    def test_func(self):
        return self.request.user.groups.filter(name__in=['Therapist']).exists()
    
    def get_queryset(self):
        user = self.request.user
        
        if user.groups.filter(name__in=['Guardian', 'Assistant']).exists():
            raise PermissionDenied
       
        return super().get_queryset()
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['patient'] = self.object  
        return context
    
    def get_success_url(self):
        return reverse_lazy('patients.details', kwargs={'pk': self.object.pk})

class PatientsDeleteView(LoginRequiredMixin, UserRoleMixin, DeleteView):
    model = PatientInformation
    template_name = "patients/patients_delete.html"
    success_url = reverse_lazy('patients.list')
    
    def test_func(self):
        return self.request.user.groups.filter(name__in=['Therapist']).exists()
    
    def get_queryset(self):
        user = self.request.user
        
        if user.groups.filter(name__in=['Guardian', 'Assistant']).exists():
            raise PermissionDenied
        
        return super().get_queryset()
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['patient'] = get_object_or_404(PatientInformation, pk=self.object.pk)  
        return context

"""
PATIENT NOTES
"""

class NoteDetailView(LoginRequiredMixin, DetailView):
    model = PatientNotes
    template_name = 'patients_notes/note_details.html'
    context_object_name = "note"
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        note = self.get_object()

        context['patient_notes'] = PatientNotes.objects.filter(patient=note.patient)

        user = self.request.user
        context['is_guardian'] = user.groups.filter(name='Guardian').exists()
        context['is_assistant'] = user.groups.filter(name='Assistant').exists()
        context['is_therapist'] = user.groups.filter(name='Therapist').exists()
        context['is_administrator'] = user.groups.filter(name='Administrator').exists()

        patient = note.patient
        context['patient'] = patient
        return context
    
    def get_queryset(self):
        user = self.request.user
        note_id = self.kwargs.get('pk')  

        try:
            note = PatientNotes.objects.get(id=note_id)  
            patient = note.patient    
        except PatientNotes.DoesNotExist:
            return PatientNotes.objects.none()  

        if user.groups.filter(name='Guardian').exists():
            patients = PatientInformation.objects.filter(account_id=user)

            if patient in patients:  
                return PatientNotes.objects.filter(patient=patient)
            else:
                return PatientNotes.objects.none()

        elif user.groups.filter(name__in=['Therapist', 'Assistant']).exists():
            return PatientNotes.objects.all()

        else:
            raise PermissionDenied


        
class NoteCreateView(RolePermissionRequiredMixin, CreateView):
    model = PatientNotes
    form_class = PatientNotesForm
    template_name = "patients_notes/note_form.html"
    allowed_roles = ['Therapist']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        patient = get_object_or_404(PatientInformation, id=self.kwargs['pk'])
        context['patient'] = patient 
        return context

    def form_valid(self, form):
        patient = get_object_or_404(PatientInformation, id=self.kwargs['pk'])
        form.instance.patient = patient
        form.instance.author = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('patients.details', kwargs={'pk': self.kwargs['pk']})

class NotesUpdateView(RolePermissionRequiredMixin, UpdateView):
    model = PatientNotes
    form_class = PatientNotesForm
    template_name = "patients_notes/note_form.html"
    allowed_roles = ['Therapist']
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        note = self.get_object()

        context['patient_notes'] = PatientNotes.objects.filter(patient=note.patient)

        user = self.request.user
        context['is_guardian'] = user.groups.filter(name='Guardian').exists()
        context['is_assistant'] = user.groups.filter(name='Assistant').exists()
        context['is_therapist'] = user.groups.filter(name='Therapist').exists()
        context['is_administrator'] = user.groups.filter(name='Administrator').exists()

        patient = note.patient
        context['patient'] = patient
        return context

    def get_success_url(self):
        return reverse('patients.details', kwargs={'pk': self.object.patient.pk})
    
class NotesDeleteView(RolePermissionRequiredMixin, DeleteView):
    model = PatientNotes 
    template_name='patients_notes/note_delete.html'
    allowed_roles = ['Therapist']
    
    def get_success_url(self):
        return reverse('patients.details', kwargs={'pk': self.object.patient.pk})

class AssignGameView(LoginRequiredMixin, View):
    def post(self, request, patient_id):
        if not request.user.groups.filter(name='Therapist').exists():
            return HttpResponseForbidden("Only therapists can assign games.")
        
        patient = get_object_or_404(PatientInformation, id=patient_id)

O4P/patients/templates/patients/patients_delete.html
{% extends 'dashboard_navbar.html' %}

{% block content %}
{% include "blobs.html" %}
<form method="POST"> {% csrf_token %}
    <p>Are you sure you want to delete "{{patient.first_name}} {{patient.last_name}}"?</p>
    <p>This action cannot be undone.</p>

    <input type="submit" class="btn btn-danger" value="Confirm"/>
</form>
    <a href="{% url 'patients.list' %}" class="btn btn-secondary my-2">Back</a>

{% endblock %}

O4P/patients/templates/patients/patients_details.html
{% extends "base.html" %}
{% block content %}

    <h1>{{ patient.first_name }} {{ patient.last_name }}</h1>
    <p>Date of Birth: {{ patient.date_of_birth }}</p>
    <p>Contact Number: {{ patient.contact_number }}</p>
    <p>City: {{ patient.city }}</p>
    <p>Province: {{ patient.province }}</p>
    <p>Condition: {{ patient.condition }}</p>

    <h2>Notes</h2>
    <table class="table">
        <thead>
            <tr>
                <th>Note Title</th>
                <th>Session Date</th>
            </tr>
        </thead>
        <tbody>
            {% for note in patient_notes %}
            <tr>
                <td>
                    <a href="{% url 'notes.details' note.id %}" class="text-blue text-decoration-none">
                        {{ note.title }}
                    </a>
                </td>
                <td>{{ note.session_date }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

    <a href="
    {% if is_patient %} 
        {% url 'welcome' %}
    {% else %} 
        {% url 'patients.list' %}
    {% endif %}" 
    class="btn btn-secondary my-5">
    Back
    </a>

    {% if is_therapist %}
        <a href="{% url 'patients.update' pk=patient.id %}" class="btn btn-secondary my-5">Edit</a>
        <a href="{% url 'patients.delete' pk=patient.id %}" class="btn btn-danger my-5">Delete</a>
    {% endif %}
{% endblock %}

O4P/patients/templates/patients/patients_form.html
{% extends "dashboard_navbar.html" %}
{% load static %}

{% block content %}
{% include "blobs.html" %}
<div class="container-fluid">
    <div class="header-1 my-2">
        <h1>Edit {{ patient.first_name }} {{ patient.last_name }}</h1>
        <div>
            <button type="submit" form="iForm" class="btn2 btn-success">Save</button>
            <a href="{% url 'patients.details' pk=patient.id %}" class="btn2 btn-danger">Cancel</a>
        </div>
    </div>

    <form id="iForm" method="POST"> 
        {% csrf_token %} 
        <div class="row gutters-sm">
            <div class="col-md-12">
                <div class="edit-card mb-3">
                    <div class="card-body">
                        <h3 class="h6 mb-3 text-secondary">Edit Personal Information</h3>
                        <hr>
                        <div class="row mb-3">
                            <div class="col-sm-4">
                                <label class="form-label">First Name</label>
                                {{ form.first_name }}
                            </div>
                            <div class="col-sm-4">
                                <label class="form-label">Middle Name</label>
                                {{ form.middle_name }}
                            </div>
                            <div class="col-sm-4">
                                <label class="form-label">Last Name</label>
                                {{ form.last_name }}
                            </div>
                        </div>
                        <div class="row mb-3">
                            <div class="col-sm-8">
                                <label class="form-label">Date of Birth</label>
                                {{ form.date_of_birth }}
                            </div>
                            <div class="col-sm-4">
                                <label class="form-label">Sex</label>
                                {{ form.sex }}
                            </div>
                        </div>
                        <div class="row mb-3">
                            <div class="col-sm-6">
                                <label class="form-label">Nationality</label>
                                {{ form.nationality }}
                            </div>
                            <div class="col-sm-6">
                                <label class="form-label">Religion</label>
                                {{ form.religion }}
                            </div>
                        </div>
                        <div class="row mb-3">
                            <div class="col-sm-12">
                                <label class="form-label">Contact Number</label>
                                {{ form.contact_number }}
                            </div>
                        </div>
                    </div>
                </div>
                <div class="edit-card mb-3">
                    <div class="card-body">
                        <h3 class="h6 mb-3 text-secondary">Edit Address</h3>
                        <hr>
                        <div class="row mb-3">
                            <div class="col-sm-6">
                                <label class="form-label">Province</label>
                                {{ form.province }}
                            </div>
                            <div class="col-sm-6">
                                <label class="form-label">Municipality</label>
                                {{ form.municipality }}
                            </div>
                        </div>
                    </div>
                </div>
                <div class="edit-card mb-3">
                    <div class="card-body">
                        <h3 class="h6 mb-3 text-secondary">Edit Medical Information</h3>
                        <hr>
                        <div class="row mb-3">
                            <div class="col-sm-8">
                                <label class="form-label">Diagnosis</label>
                                {{ form.diagnosis }}
                            </div>
                            <div class="col-sm-4">
                                <label class="form-label">Referring Doctor</label>
                                {{ form.referring_doctor }}
                            </div>
                        </div>
                        <div class="row mb-3">
                            <div class="col-sm-6">
                                <label class="form-label">Mother's Name</label>
                                {{ form.mother_name }}
                            </div>
                            <div class="col-sm-6">
                                <label class="form-label">Mother's Contact Number</label>
                                {{ form.mother_number }}
                            </div>
                        </div>
                        <div class="row mb-3">
                            <div class="col-sm-6">
                                <label class="form-label">Father's Name</label>
                                {{ form.father_name }}
                            </div>
                            <div class="col-sm-6">
                                <label class="form-label">Father's Contact Number</label>
                                {{ form.father_number }}
                            </div>
                        </div>
                        <div class="row mb-3">
                            <div class="col-sm-12">
                                <label class="form-label">School</label>
                                {{ form.school }}
                            </div>
                        </div>
                        <div class="row mb-3">
                            <div class="col-sm-12">
                                <label class="form-label">Relationship to Guardian</label>
                                {{ form.relationship_to_guardian }}
                            </div>
                        </div>
                        <div class="row mb-3">
                            <div class="col-sm-12">
                                <label class="form-label">Initial Evaluation</label>
                                {{ form.initial_evaluation }}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
    {% if form.errors %}
        <div class="alert alert-danger my-5">
            {{ form.errors.as_text }}
        </div>
    {% endif %}
</div>

<script>
    document.getElementById('id_province').addEventListener('change', function() {
        console.log("HELLO THERE");
        const provinceCode = this.value;
        const municipalitySelect = document.getElementById('id_municipality');
    
        municipalitySelect.innerHTML = '<option value="">---------</option>'; 
    
        if (!provinceCode) return;
    
        fetch(`/get-municipalities/?province_code=${encodeURIComponent(provinceCode)}`)
            .then(response => response.json())
            .then(data => {
                data.municipalities.forEach(municipality => {
                    const option = new Option(municipality.name, municipality.code);
                    municipalitySelect.appendChild(option);
                });
            })
            .catch(error => console.error('Error:', error));
    });
</script>

{% endblock %}

O4P/patients/templates/patients/patients_list.html
{% extends "dashboard_navbar.html" %}

{% block content %}
{% include "blobs.html" %}
<div class="container-fluid">
  <div class="header-1">
    <h1>List of Patients</h1>
  </div>

  <div class="header-search">
      <form method="GET" action="{% url 'patients.list' %}" class="search-form">
        <input class="search-bar" placeholder="Search Patient" type="text" name="q" value="{{ search_query }}">
        <button type="submit" class="search-button">
          🔍
        </button>
      </form>
  </div>

  <div class="table-container">
    <table class="custom-table">
      <thead>
        <tr>
          <th>Name</th>
          <th>Diagnosis</th>
          <th>Sex</th>
          <th>Date of Birth</th>
          <th>Assigned Guardian</th>
        </tr>
      </thead>
      <tbody>
        {% for patient in patients %}
          <tr>
            <td>
              <a href="{% url 'patients.details' pk=patient.id %}" class="text-dark text-decoration-none">
                {{ patient.first_name }} {% if patient.middle_name %} {{patient.middle_name}} {% endif %} {{ patient.last_name }}
              </a>
            </td>
            <td>
              <a href="{% url 'patients.details' pk=patient.id %}" class="text-dark text-decoration-none">
                {{ patient.diagnosis }}
              </a>
            </td>
            <td>
              <a href="{% url 'patients.details' pk=patient.id %}" class="text-dark text-decoration-none">
                {{ patient.sex }} 
              </a>
            </td>
            <td>
              <a href="{% url 'patients.details' pk=patient.id %}" class="text-dark text-decoration-none">
                {{ patient.date_of_birth }}
              </a>
            </td>
            <td>
              <a href="{% url 'patients.details' pk=patient.id %}" class="text-dark text-decoration-none">
                {{ patient.account_id.guardianinformation_set.first.first_name}} 
                {% if patient.account_id.guardianinformation_set.first.middle_name %}
                {{ patient.account_id.guardianinformation_set.first.middle_name}} 
                {% endif %}
                {{ patient.account_id.guardianinformation_set.first.last_name}}  
              </a>
            </td>
          </tr>
        {% endfor %}
        
        {% if not patients %}
          <tr>
            <td colspan="4">
              <h6>No patients available.</h6>  
            </td>
          </tr>
        {% endif %}
      </tbody>
    </table>
  </div>
  
  <div class="my-3">
    <a href="{% url 'welcome' %}" class="btn">Back</a>

    {% if is_guardian%}
    <a href="{% url 'patients.create' %}" class="btn">Add Patient</a>
    {% endif %}
  </div>
</div>
{% endblock %}